Handle XPathEvalError
We saw a case in production where 'div:nth-child(6)' was parsed as valid
xpath but couldn't eval. That's a bug in libxpath, sure ... but we _do_
need to handle syntactically-valid xpath that can't eval, so the xpath
bug isn't worth pursuing.

Fixes warning+error on production

Warning: xmlXPathCompOpEval: function nth-child bound to undefined prefix div

Error:

Exception in scrapexpathlist.fetch
Traceback (most recent call last):
  File "/app/server/models/loaded_module.py", line 207, in fetch
    out = await future_result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/minio_downloadr4rod_6w", line 33, in fetch
  File "/tmp/minio_downloadr4rod_6w", line 136, in do_fetch
  File "/tmp/minio_downloadr4rod_6w", line 96, in select
  File "src/lxml/xpath.pxi", line 445, in lxml.etree.XPath.__call__
  File "src/lxml/xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result
lxml.etree.XPathEvalError: Error in xpath expression